# Pandas 数据清洗实战

**学习目标：** 掌握 Pandas 的增删改查、去重、数据类型转换，对大众点评原始评论数据进行初步清洗。

**产出：** 清洗后的干净数据集 `clean_data.csv`

## 1. 环境准备与数据加载

In [1]:
import pandas as pd
import numpy as np
import os

# 设置显示选项
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

DATA_PATH = 'data1.csv'
df = pd.read_csv(DATA_PATH)
print(f'原始数据形状: {df.shape}')
df.head()

原始数据形状: (32483, 14)

        cus_id         comment_time comment_star                                        cus_comment kouwei huanjing fuwu  shopID  stars  year  month  weekday  hour  comment_len
0         迷糊泰迪  2018-09-20 06:48:00    sml-str40  南信 算是 广州 著名 甜品店 吧 好几个 时间段 路过 都 是 座无虚席 看着 餐单 上 ...    非常好        好    好  518986    4.0  2018      9        3     6          184
1        稱霸幼稚園  2018-09-22 21:49:00    sml-str40  中午 吃 完 了 所谓 的 早茶 回去 放下 行李 休息 了 会 就 来 吃 下午茶 了 服...     很好       很好   很好  518986    4.0  2018      9        5    21          266
2       爱吃的美美侠  2018-09-22 22:16:00    sml-str40  冲刺 王者 战队 吃遍 蓉城 战队 有 特权 五月份 和 好 朋友 毕业 旅行 来 了 广州...     很好       很好   很好  518986    4.0  2018      9        5    22          341
3        姜姜会吃胖  2018-09-19 06:36:00    sml-str40  都 说来 广州 吃 糖水 就要 来南信 招牌 姜撞奶 红豆 双皮奶 牛 三星 云吞面 一楼 ...    非常好       很好   很好  518986    4.0  2018      9        2     6          197
4  forevercage  2018-08-24 17:58:00    sml-str50  一直 很 期待 也 最 爱 吃 甜品 广州 的 甜品 很 丰富 很 多样 来 之前 就 一直...    非常好       很好   很好  518986    5.0  2018      8        4    17          261

## 2. 数据探索（查）

使用 `info()`、`describe()`、`isnull()` 了解数据结构与质量。

In [2]:
# 查看数据类型与内存占用
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32483 entries, 0 to 32482
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cus_id        32483 non-null  object
 1   comment_time  32483 non-null  object
 2   comment_star  32483 non-null  object
 3   cus_comment   32474 non-null  object
 4   kouwei        32483 non-null  object
 5   huanjing      32483 non-null  object
 6   fuwu          32483 non-null  object
 7   shopID        32483 non-null  int64
 8   stars         26847 non-null  float64
 9   year          32483 non-null  int64
 10  month         32483 non-null  int64
 11  weekday       32483 non-null  int64
 12  hour          32483 non-null  int64
 13  comment_len   32483 non-null  int64
dtypes: float64(1), int64(6), object(7)
memory usage: 3.5+ MB

In [3]:
# 数值型字段统计描述
df.describe()

             shopID         stars          year         month       weekday          hour   comment_len
count  3.248300e+04  26847.000000  32483.000000  32483.000000  32483.000000  32483.000000  32483.000000
mean   9.729449e+05      3.983611   2013.951113      6.445956      3.022258     14.913155    126.145984
std    9.148846e+05      0.971025      3.678126      3.363897      2.025748      6.027981    118.718559
min    5.189860e+05      1.000000   2004.000000      1.000000      0.000000      0.000000      0.000000
25%    5.189860e+05      3.000000   2011.000000      4.000000      1.000000     11.000000     40.000000
50%    5.200040e+05      4.000000   2015.000000      6.000000      3.000000     16.000000     74.000000
75%    5.203560e+05      5.000000   2017.000000      9.000000      5.000000     20.000000    193.000000
max    3.456244e+06      5.000000   2018.000000     12.000000      6.000000     23.000000   1957.000000

In [4]:
# 缺失值统计
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
pd.DataFrame({'缺失数': missing, '缺失率%': missing_pct})

               缺失数   缺失率%
cus_id           0   0.00
comment_time     0   0.00
comment_star     0   0.00
cus_comment      9   0.03
kouwei           0   0.00
huanjing         0   0.00
fuwu             0   0.00
shopID           0   0.00
stars         5636  17.35
year             0   0.00
month            0   0.00
weekday          0   0.00
hour             0   0.00
comment_len      0   0.00

In [5]:
# 查看各字段唯一值数量
df.nunique()

cus_id          27472
comment_time    32234
comment_star        6
cus_comment     32437
kouwei              6
huanjing            6
fuwu                6
shopID              8
stars               5
year               15
month              12
weekday             7
hour               24
comment_len       713
dtype: int64

## 3. 增删改查实战

### 3.1 查 — 条件筛选与列选择

In [6]:
# 筛选高评分评论（stars >= 4.5）
high_rating = df[df['stars'] >= 4.5]
print(f'高评分评论数: {len(high_rating)}')

# 选择特定列
df[['cus_id', 'shopID', 'stars', 'comment_time']].head()

高评分评论数: 9067

        cus_id  shopID  stars         comment_time
0         迷糊泰迪  518986    4.0  2018-09-20 06:48:00
1        稱霸幼稚園  518986    4.0  2018-09-22 21:49:00
2       爱吃的美美侠  518986    4.0  2018-09-22 22:16:00
3        姜姜会吃胖  518986    4.0  2018-09-19 06:36:00
4  forevercage  518986    5.0  2018-08-24 17:58:00

In [7]:
# 按门店分组统计评论数
shop_stats = df.groupby('shopID').agg(
    评论数=('cus_id', 'count'),
    平均评分=('stars', 'mean'),
    平均评论长度=('comment_len', 'mean')
).round(2)
shop_stats.sort_values('评论数', ascending=False)

           评论数  平均评分  平均评论长度
shopID
518986   13970  4.08  128.01
520004    7589  3.89  123.01
1893229   2893  3.94  137.20
520356    2814  3.83  152.61
3456244   1701  4.27   38.40
3179845   1353  3.73  140.94
2447053   1120  3.70  133.88
521698    1043  3.95  137.59

### 3.2 — 新增衍生列

In [8]:
# 新增评分等级列
def rating_level(star):
    if pd.isna(star):
        return '未知'
    if star >= 4.5:
        return '好评'
    elif star >= 3.5:
        return '中评'
    else:
        return '差评'

df['rating_level'] = df['stars'].apply(rating_level)
df['rating_level'].value_counts()

rating_level
中评    10849
好评     9067
差评     6931
未知     5636
Name: count, dtype: int64

In [9]:
# 新增评论时段列
def time_period(hour):
    if 6 <= hour < 11:
        return '上午'
    elif 11 <= hour < 14:
        return '中午'
    elif 14 <= hour < 18:
        return '下午'
    elif 18 <= hour < 22:
        return '晚上'
    else:
        return '深夜/凌晨'

df['time_period'] = df['hour'].apply(time_period)
df['time_period'].value_counts()

time_period
下午       8129
晚上       7489
深夜/凌晨    7410
中午       5542
上午       3913
Name: count, dtype: int64

### 3.3 改 — 修改数据值

In [10]:
# 将 comment_star 中的 NAN 字符串统一处理
print('修改前:', df['comment_star'].value_counts().get('NAN', 0))
df.loc[df['comment_star'] == 'NAN', 'comment_star'] = np.nan
print('修改后 NAN 数量:', df['comment_star'].isna().sum())

修改前: 5636
修改后 NAN 数量: 5636

### 3.4 删 — 删除列或行

In [11]:
# 演示：删除临时列（清洗流程中会保留有用列）
demo_df = df.copy()
demo_df = demo_df.drop(columns=['time_period'])
print(f'删除列后形状: {demo_df.shape}')

删除列后形状: (32483, 15)

## 4. 去重

In [12]:
print(f'重复行数量: {df.duplicated().sum()}')
print(f'完全重复行: {df.duplicated(keep=False).sum()}')

# 基于用户+门店+评论时间去重（业务逻辑去重）
dup_mask = df.duplicated(subset=['cus_id', 'shopID', 'comment_time'], keep='first')
print(f'业务重复评论: {dup_mask.sum()}')

重复行数量: 22
完全重复行: 44
业务重复评论: 22

## 5. 数据类型转换

In [13]:
# comment_time 转为 datetime
df['comment_time'] = pd.to_datetime(df['comment_time'])
print(df['comment_time'].dtype)
print(f'时间范围: {df["comment_time"].min()} ~ {df["comment_time"].max()}')

datetime64[ns]
时间范围: 2004-07-05 13:42:00 ~ 2018-09-27 07:44:00

In [14]:
# comment_star 映射为数值评分
star_map = {
    'sml-str50': 5.0,
    'sml-str40': 4.0,
    'sml-str30': 3.0,
    'sml-str20': 2.0,
    'sml-str10': 1.0
}
df['star_from_comment'] = df['comment_star'].map(star_map)

# 用映射值填充 stars 缺失
df['stars'] = df['stars'].fillna(df['star_from_comment'])
print(f'stars 缺失数（填充后）: {df["stars"].isna().sum()}')

stars 缺失数（填充后）: 5636

In [15]:
# shopID 转为字符串类型（便于后续合并）
df['shopID'] = df['shopID'].astype(str)
df.dtypes

cus_id                       object
comment_time         datetime64[ns]
comment_star                 object
cus_comment                  object
kouwei                       object
huanjing                     object
fuwu                         object
shopID                       object
stars                       float64
year                          int64
month                         int64
weekday                       int64
hour                          int64
comment_len                   int64
rating_level                 object
time_period                  object
star_from_comment           float64
dtype: object

## 6. 处理缺失值

In [16]:
# cus_comment 缺失：用空字符串填充
df['cus_comment'] = df['cus_comment'].fillna('')

# 维度评分缺失检查
for col in ['kouwei', 'huanjing', 'fuwu']:
    print(f'{col} 缺失: {df[col].isna().sum()}')

print(f'\n清洗后总缺失: {df.isnull().sum().sum()}')

kouwei 缺失: 0
huanjing 缺失: 0
fuwu 缺失: 0

清洗后总缺失: 16908

## 7. 处理异常值

In [17]:
# 评论长度为 0 的异常记录
zero_len = df[df['comment_len'] == 0]
print(f'评论长度为0的记录: {len(zero_len)}')
zero_len[['cus_id', 'cus_comment', 'comment_len', 'stars']]

评论长度为0的记录: 2

     cus_id cus_comment  comment_len  stars
9403  虎斑大花猫                        0    5.0
9404     C程                        0    3.0

In [18]:
# 使用 IQR 方法检测评论长度异常值
Q1 = df['comment_len'].quantile(0.25)
Q3 = df['comment_len'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['comment_len'] < lower_bound) | (df['comment_len'] > upper_bound)]
print(f'评论长度异常值数量: {len(outliers)} ({len(outliers)/len(df)*100:.1f}%)')
print(f'正常范围: [{max(0, lower_bound):.0f}, {upper_bound:.0f}]')

评论长度异常值数量: 702 (2.2%)
正常范围: [0, 422]

In [19]:
# 评分异常值检查（应在 1-5 之间）
invalid_stars = df[(df['stars'] < 1) | (df['stars'] > 5)]
print(f'评分超出范围记录: {len(invalid_stars)}')

评分超出范围记录: 0

## 8. 综合清洗流程

In [20]:
def clean_dianping_data(raw_df):
    """大众点评评论数据清洗流水线"""
    data = raw_df.copy()
    
    # 1. comment_star 标准化
    data.loc[data['comment_star'] == 'NAN', 'comment_star'] = np.nan
    
    # 2. 时间类型转换
    data['comment_time'] = pd.to_datetime(data['comment_time'])
    
    # 3. 评分填充
    star_map = {'sml-str50': 5.0, 'sml-str40': 4.0, 'sml-str30': 3.0,
                'sml-str20': 2.0, 'sml-str10': 1.0}
    data['stars'] = data['stars'].fillna(data['comment_star'].map(star_map))
    
    # 4. 缺失值处理
    data['cus_comment'] = data['cus_comment'].fillna('')
    
    # 5. 去重
    data = data.drop_duplicates(subset=['cus_id', 'shopID', 'comment_time'], keep='first')
    data = data.drop_duplicates(keep='first')
    
    # 6. 异常值过滤：保留有效评分和合理评论长度
    data = data[(data['stars'] >= 1) & (data['stars'] <= 5)]
    data = data[data['comment_len'] >= 0]
    
    # 7. 衍生列
    data['rating_level'] = data['stars'].apply(
        lambda s: '好评' if s >= 4.5 else ('中评' if s >= 3.5 else '差评')
    )
    data['shopID'] = data['shopID'].astype(str)
    
    return data.reset_index(drop=True)

# 重新加载原始数据执行清洗
raw_df = pd.read_csv(DATA_PATH)
clean_df = clean_dianping_data(raw_df)
print(f'原始: {raw_df.shape} -> 清洗后: {clean_df.shape}')
clean_df.head()

原始: (32483, 14) -> 清洗后: (26825, 15)

        cus_id        comment_time comment_star                                        cus_comment kouwei huanjing fuwu  shopID  stars  year  month  weekday  hour  comment_len rating_level
0         迷糊泰迪 2018-09-20 06:48:00    sml-str40  南信 算是 广州 著名 甜品店 吧 好几个 时间段 路过 都 是 座无虚席 看着 餐单 上 ...    非常好        好    好  518986    4.0  2018      9        3     6          184           中评
1        稱霸幼稚園 2018-09-22 21:49:00    sml-str40  中午 吃 完 了 所谓 的 早茶 回去 放下 行李 休息 了 会 就 来 吃 下午茶 了 服...     很好       很好   很好  518986    4.0  2018      9        5    21          266           中评
2       爱吃的美美侠 2018-09-22 22:16:00    sml-str40  冲刺 王者 战队 吃遍 蓉城 战队 有 特权 五月份 和 好 朋友 毕业 旅行 来 了 广州...     很好       很好   很好  518986    4.0  2018      9        5    22          341           中评
3        姜姜会吃胖 2018-09-19 06:36:00    sml-str40  都 说来 广州 吃 糖水 就要 来南信 招牌 姜撞奶 红豆 双皮奶 牛 三星 云吞面 一楼 ...    非常好       很好   很好  518986    4.0  2018      9        2     6          197           中评
4  forevercage 2018-08-24 17:58:00    sml-str50  一直 很 期待 也 最 爱 吃 甜品 广州 的 甜品 很 丰富 很 多样 来 之前 就 一直...    非常好       很好   很好  518986    5.0  2018      8        4    17          261           好评

## 9. 保存清洗后数据

In [21]:
OUTPUT_PATH = 'clean_data.csv'
clean_df.to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
print(f'已保存至 {OUTPUT_PATH}')
print(f'文件大小: {os.path.getsize(OUTPUT_PATH)/1024/1024:.2f} MB')

已保存至 clean_data.csv
文件大小: 10.61 MB

## 10. 清洗前后对比总结

In [22]:
summary = pd.DataFrame({
    '指标': ['总行数', '缺失stars', '重复行', '门店数', '平均评分', '平均评论长度'],
    '清洗前': [
        len(raw_df),
        raw_df['stars'].isna().sum(),
        raw_df.duplicated().sum(),
        raw_df['shopID'].nunique(),
        round(raw_df['stars'].mean(), 2),
        round(raw_df['comment_len'].mean(), 1)
    ],
    '清洗后': [
        len(clean_df),
        clean_df['stars'].isna().sum(),
        clean_df.duplicated().sum(),
        clean_df['shopID'].nunique(),
        round(clean_df['stars'].mean(), 2),
        round(clean_df['comment_len'].mean(), 1)
    ]
})
summary

        指标       清洗前       清洗后
0      总行数  32483.00  26825.00
1  缺失stars   5636.00      0.00
2      重复行     22.00      0.00
3      门店数      8.00      8.00
4     平均评分      3.98      3.98
5   平均评论长度    126.10    128.60